# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ba2d753645c7c3f80e486c85c84b7d481a504609cddfd37e22744af89b0b483a3f27ca523558dabba035bcbef5fa5ff12b6a0e060d1d15ffc549efbc8a05d0cd

test:
  secret_key_base: 9a36590fbac98671333ffa04435fb723feb1888b74dd44cba0010ff936ff97daecdef33061651019ba5fa6a2664e503a3680b3173feb36eb75920789ea0fb278

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
